services:
  database:
    container_name: dee-database-p2
    environment:
      POSTGRES_DB: dee_meetings_p2
    ports:
      - "5433:5432"
    networks:
      - dee-network-p2

  backend:
    container_name: dee-backend-p2
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:amit2004@dee-database-p2:5432/dee_meetings_p2"
      DIRECT_URL: "postgresql://postgres:amit2004@dee-database-p2:5432/dee_meetings_p2"
    networks:
      - dee-network-p2

  frontend:
    container_name: dee-frontend-p2
    ports:
      - "802:80"
    build:
      args:
        VITE_API_URL: "http://192.168.0.131:802/api"
    networks:
      - dee-network-p2

volumes:
  postgres_data_p2:

networks:
  dee-network-p2:
    driver: bridge